// ryzc — RYZ native code generator. Transpiles RYZ -> C for gcc, producing
// standalone ELF executables AND shared libraries (.so) — so ryz transcends its
// interpreter (no bun/node at runtime) and ships its own LIBS.
//
// Supported core subset (grows via Task #52): fn/export fn, let/mut, i*/u*/f*/string/bool,
// arithmetic + comparison + && || !, if/else/while, return, recursion, fmt.println/print.
import { lex } from "../bun/src/lexer";
import { parse } from "../bun/src/parser";
import type * as A from "../bun/src/ast";

type CType = "long long" | "double" | "const char*" | "int" | "void";

function ryzTypeToC(t: string | undefined): CType {
  switch (t) {
    case "f32": case "f64": return "double";
    case "string": return "const char*";
    case "bool": return "int";
    case "i8": case "i16": case "i32": case "u8": case "u16": case "u32": return "int";
    case "i64": case "u64": return "long long";
    case undefined: return "long long";
    default: return "long long";
  }
}

function cEscape(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n").replace(/\t/g, "\\t").replace(/\r/g, "\\r");
}

export class RyzcError extends Error {}

class Codegen {
  private fnRet = new Map<string, CType>();
  private fnExported = new Map<string, boolean>();

  constructor(private prog: A.Program) {}

  generate(mode: "exec" | "lib"): string {
    const fns = this.prog.body.filter((n): n is A.FnDecl => n.kind === "FnDecl");
    for (const f of fns) { this.fnRet.set(f.name, ryzTypeToC(f.retType)); this.fnExported.set(f.name, f.exported); }

    const out: string[] = [];
    out.push("// generated by ryzc (RYZ native backend)");
    out.push("#include <stdio.h>");
    out.push("#include <string.h>");
    out.push("");
    // prototypes
    for (const f of fns) if (f.name !== "main") out.push(this.signature(f) + ";");
    out.push("");
    // definitions
    for (const f of fns) {
      if (f.name === "main" && mode === "lib") continue; // libs don't emit main
      out.push(this.emitFn(f, mode));
      out.push("");
    }
    if (mode === "exec" && !fns.some((f) => f.name === "main")) {
      out.push("int main(void){return 0;}");
    }
    return out.join("\n");
  }

  private signature(f: A.FnDecl): string {
    if (f.name === "main") return "int main(void)";
    const ret = ryzTypeToC(f.retType);
    const params = f.params.map((p) => `${ryzTypeToC(p.type)} ${p.name}`).join(", ") || "void";
    const vis = f.exported ? "" : "static "; // non-exported -> file-local; exported -> public (lib ABI)
    return `${vis}${ret} ${f.name}(${params})`;
  }

  private emitFn(f: A.FnDecl, mode: "exec" | "lib"): string {
    const scope = new Map<string, CType>();
    for (const p of f.params) scope.set(p.name, ryzTypeToC(p.type));
    const sig = f.name === "main" ? "int main(void)" : this.signature(f);
    const body = this.emitBlock(f.body, scope, 1);
    let tail = "";
    if (f.name === "main") tail = "\n    return 0;"; // ensure main returns int even if ryz main returns via paths
    return `${sig} {\n${body}${tail}\n}`;
  }

  private indent(n: number) { return "    ".repeat(n); }

  private emitBlock(b: A.Block, scope: Map<string, CType>, depth: number): string {
    const lines: string[] = [];
    for (const s of b.body) lines.push(this.emitStmt(s, scope, depth));
    return lines.filter((l) => l.length).join("\n");
  }

  private emitStmt(n: A.Node, scope: Map<string, CType>, depth: number): string {
    const ind = this.indent(depth);
    switch (n.kind) {
      case "LetStmt": {
        const ct = this.typeOf(n.value, scope);
        scope.set(n.name, ct);
        return `${ind}${ct} ${n.name} = ${this.emitExpr(n.value, scope)};`;
      }
      case "Assign": {
        if (n.target.kind !== "Ident") throw new RyzcError("native backend: only simple assignment supported (Task #52)");
        return `${ind}${(n.target as A.Ident).name} = ${this.emitExpr(n.value, scope)};`;
      }
      case "ReturnStmt":
        return `${ind}return ${n.value ? this.emitExpr(n.value, scope) : "0"};`;
      case "IfStmt": {
        let s = `${ind}if (${this.emitExpr(n.cond, scope)}) {\n${this.emitBlock(n.then, new Map(scope), depth + 1)}\n${ind}}`;
        if (n.else) {
          if (n.else.kind === "Block") s += ` else {\n${this.emitBlock(n.else, new Map(scope), depth + 1)}\n${ind}}`;
          else s += ` else ${this.emitStmt(n.else, scope, depth).trimStart()}`;
        }
        return s;
      }
      case "WhileStmt":
        return `${ind}while (${this.emitExpr(n.cond, scope)}) {\n${this.emitBlock(n.body, new Map(scope), depth + 1)}\n${ind}}`;
      case "ExprStmt":
        return this.emitExprStmt(n.expr, scope, depth);
      case "Block":
        return `${ind}{\n${this.emitBlock(n, new Map(scope), depth + 1)}\n${ind}}`;
      default:
        throw new RyzcError(`native backend: statement '${n.kind}' not yet supported (Task #52)`);
    }
  }

  // handle fmt.println / fmt.print specially -> printf
  private emitExprStmt(e: A.Node, scope: Map<string, CType>, depth: number): string {
    const ind = this.indent(depth);
    if (e.kind === "Call" && e.callee.kind === "Member") {
      const m = e.callee as A.Member;
      if (m.object.kind === "Ident" && (m.object as A.Ident).name === "fmt" && (m.property === "println" || m.property === "print")) {
        const fmts: string[] = []; const args: string[] = [];
        e.args.forEach((a, i) => {
          const t = this.typeOf(a, scope);
          fmts.push(t === "const char*" ? "%s" : t === "double" ? "%f" : t === "int" ? "%d" : "%lld");
          args.push(this.emitExpr(a, scope));
        });
        const fmt = fmts.join(" ") + (m.property === "println" ? "\\n" : "");
        const argList = args.length ? ", " + args.join(", ") : "";
        return `${ind}printf("${fmt}"${argList});`;
      }
    }
    return `${ind}${this.emitExpr(e, scope)};`;
  }

  private typeOf(e: A.Node, scope: Map<string, CType>): CType {
    switch (e.kind) {
      case "IntLit": return "long long";
      case "FloatLit": return "double";
      case "StrLit": return "const char*";
      case "BoolLit": return "int";
      case "Ident": return scope.get(e.name) ?? "long long";
      case "Unary": return e.op === "!" ? "int" : this.typeOf(e.operand, scope);
      case "Binary": {
        if (["<", ">", "<=", ">=", "==", "!=", "&&", "||"].includes(e.op)) return "int";
        const lt = this.typeOf(e.left, scope), rt = this.typeOf(e.right, scope);
        return lt === "double" || rt === "double" ? "double" : "long long";
      }
      case "Call":
        if (e.callee.kind === "Ident") return this.fnRet.get((e.callee as A.Ident).name) ?? "long long";
        return "long long";
      case "Assign": return this.typeOf(e.value, scope);
      default: return "long long";
    }
  }

  private emitExpr(e: A.Node, scope: Map<string, CType>): string {
    switch (e.kind) {
      case "IntLit": return `${e.value}LL`;
      case "FloatLit": return `${e.value}`;
      case "StrLit": return `"${cEscape(e.value)}"`;
      case "BoolLit": return e.value ? "1" : "0";
      case "Ident": return e.name;
      case "Unary": return `(${e.op}${this.emitExpr(e.operand, scope)})`;
      case "Binary": return `(${this.emitExpr(e.left, scope)} ${e.op} ${this.emitExpr(e.right, scope)})`;
      case "Call": {
        if (e.callee.kind !== "Ident") throw new RyzcError("native backend: only direct function calls supported (Task #52)");
        const args = e.args.map((a) => this.emitExpr(a, scope)).join(", ");
        return `${(e.callee as A.Ident).name}(${args})`;
      }
      case "Assign": {
        if (e.target.kind !== "Ident") throw new RyzcError("native backend: only simple assignment supported (Task #52)");
        return `(${(e.target as A.Ident).name} = ${this.emitExpr(e.value, scope)})`;
      }
      default:
        throw new RyzcError(`native backend: expression '${e.kind}' not yet supported (Task #52)`);
    }
  }
}

export function ryzToC(src: string, mode: "exec" | "lib" = "exec"): string {
  return new Codegen(parse(lex(src))).generate(mode);
}
